// TEMPORARY DATA

export let role = "admin"; // Change this to "admin", "teacher", "parent" as needed

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Dr. Anand Kumar",
    email: "anand.kumar@example.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543210",
    subjects: ["Math", "Geometry"],
    classes: ["1A", "2B", "3C"],
    address: "Powai, Maharashtra",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Ms. Preeti Sharma",
    email: "preeti.sharma@example.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543211",
    subjects: ["Physics", "Chemistry"],
    classes: ["4B", "5A", "5B"],
    address: "Dwarka, Delhi",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mr. Ramesh Iyer",
    email: "ramesh.iyer@example.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543212",
    subjects: ["Biology"],
    classes: ["7A", "6B", "6C"],
    address: "Adyar, Tamil Nadu",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Mrs. Shweta Singh",
    email: "shweta.singh@example.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543213",
    subjects: ["History"],
    classes: ["6D", "1A", "2B"],
    address: "Lucknow, Uttar Pradesh",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Ms. Divya Menon",
    email: "divya.menon@example.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543214",
    subjects: ["Music", "History"],
    classes: ["3C", "4B", "5A"],
    address: "Whitefield, Karnataka",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Mr. Arjun Reddy",
    email: "arjun.reddy@example.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543215",
    subjects: ["Physics"],
    classes: ["5B", "7A", "6B"],
    address: "Hyderabad, Telangana",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Mrs. Pooja Patel",
    email: "pooja.patel@example.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543216",
    subjects: ["English", "Spanish"],
    classes: ["6C", "6D", "1A"],
    address: "Ahmedabad, Gujarat",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Mr. Rajesh Nair",
    email: "rajesh.nair@example.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543217",
    subjects: ["Math", "Geometry"],
    classes: ["2B", "3C", "4B"],
    address: "Ernakulam, Kerala",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Ms. Anjali Dubey",
    email: "anjali.dubey@example.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543218",
    subjects: ["Literature", "English"],
    classes: ["5A", "5B", "7A"],
    address: "Kolkata, West Bengal",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Mr. Vijay Singh",
    email: "vijay.singh@example.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543219",
    subjects: ["Biology"],
    classes: ["6B", "6C", "6D"],
    address: "Jaipur, Rajasthan",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Rahul Gupta",
    email: "rahul.gupta@example.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543220",
    grade: 5,
    class: "1A",
    address: "Koramangala, Karnataka",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543221",
    grade: 5,
    class: "2B",
    address: "Pune, Maharashtra",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Arjun Reddy",
    email: "arjun.reddy.std@example.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543222",
    grade: 5,
    class: "3C",
    address: "Hyderabad, Telangana",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Neha Singh",
    email: "neha.singh@example.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543223",
    grade: 5,
    class: "4B",
    address: "New Delhi, Delhi",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Siddharth Menon",
    email: "siddharth.menon@example.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543224",
    grade: 5,
    class: "5A",
    address: "Chennai, Tamil Nadu",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Ananya Rao",
    email: "ananya.rao@example.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543225",
    grade: 5,
    class: "5B",
    address: "Bengaluru, Karnataka",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Rohan Kumar",
    email: "rohan.kumar@example.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543226",
    grade: 5,
    class: "7A",
    address: "Kolkata, West Bengal",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ishita Parekh",
    email: "ishita.parekh@example.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543227",
    grade: 5,
    class: "6B",
    address: "Ahmedabad, Gujarat",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Aryan Das",
    email: "aryan.das@example.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543228",
    grade: 5,
    class: "6C",
    address: "New Delhi, Delhi",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Sonia Devi",
    email: "sonia.devi@example.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543229",
    grade: 5,
    class: "6D",
    address: "Madurai, Tamil Nadu",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Mr. Anil Kumar",
    students: ["Rahul Gupta"],
    email: "anil.kumar@example.com",
    phone: "9876543230",
    address: "Koramangala, Karnataka",
  },
  {
    id: 2,
    name: "Mrs. Meera Sharma",
    students: ["Priya Sharma"],
    email: "meera.sharma@example.com",
    phone: "9876543231",
    address: "Pune, Maharashtra",
  },
  {
    id: 3,
    name: "Mr. Suresh Reddy",
    students: ["Arjun Reddy"],
    email: "suresh.reddy@example.com",
    phone: "9876543232",
    address: "Hyderabad, Telangana",
  },
  {
    id: 4,
    name: "Mrs. Kavita Singh",
    students: ["Neha Singh", "Rohan Singh"],
    email: "kavita.singh@example.com",
    phone: "9876543233",
    address: "New Delhi, Delhi",
  },
  {
    id: 5,
    name: "Mr. Prakash Menon",
    students: ["Siddharth Menon"],
    email: "prakash.menon@example.com",
    phone: "9876543234",
    address: "Chennai, Tamil Nadu",
  },
  {
    id: 6,
    name: "Mrs. Lakshmi Rao",
    students: ["Ananya Rao"],
    email: "lakshmi.rao@example.com",
    phone: "9876543235",
    address: "Bengaluru, Karnataka",
  },
  {
    id: 7,
    name: "Mr. Sameer Kumar",
    students: ["Rohan Kumar", "Diya Kumar"],
    email: "sameer.kumar@example.com",
    phone: "9876543236",
    address: "Kolkata, West Bengal",
  },
  {
    id: 8,
    name: "Mrs. Renuka Parekh",
    students: ["Ishita Parekh"],
    email: "renuka.parekh@example.com",
    phone: "9876543237",
    address: "Ahmedabad, Gujarat",
  },
  {
    id: 9,
    name: "Mr. Alok Das",
    students: ["Aryan Das", "Mira Das"],
    email: "alok.das@example.com",
    phone: "9876543238",
    address: "New Delhi, Delhi",
  },
  {
    id: 10,
    name: "Mrs. Gayatri Devi",
    students: ["Sonia Devi"],
    email: "gayatri.devi@example.com",
    phone: "9876543239",
    address: "Madurai, Tamil Nadu",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Dr. Anand Kumar", "Mr. Rajesh Nair"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Mrs. Pooja Patel", "Ms. Anjali Dubey"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Ms. Preeti Sharma", "Mr. Arjun Reddy"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Ms. Preeti Sharma", "Mr. Ramesh Iyer"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Mr. Ramesh Iyer", "Mr. Vijay Singh"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Mrs. Shweta Singh", "Ms. Divya Menon"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Mrs. Shweta Singh", "Mr. Vijay Singh"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Ms. Divya Menon", "Mrs. Pooja Patel"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Ms. Divya Menon", "Ms. Anjali Dubey"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Ms. Anjali Dubey", "Dr. Anand Kumar"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Mr. Rohit Sharma",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Ms. Priya Singh",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Mr. Vikram Rao",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Mrs. Sneha Gupta",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Dr. Anand Kumar",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Ms. Divya Menon",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Mr. Arjun Reddy",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Mrs. Pooja Patel",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Mr. Rajesh Nair",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ms. Anjali Dubey",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Dr. Anand Kumar",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Ms. Anjali Dubey",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Mr. Ramesh Iyer",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Mrs. Shweta Singh",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Ms. Divya Menon",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Ms. Divya Menon",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Mrs. Shweta Singh",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Mr. Vijay Singh",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ms. Preeti Sharma",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Ms. Preeti Sharma",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Dr. Anand Kumar",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Ms. Anjali Dubey",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Mr. Ramesh Iyer",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Mrs. Shweta Singh",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Ms. Divya Menon",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Ms. Divya Menon",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Mrs. Shweta Singh",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Mr. Vijay Singh",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Ms. Preeti Sharma",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Ms. Preeti Sharma",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Dr. Anand Kumar",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Ms. Anjali Dubey",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Mr. Ramesh Iyer",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Mrs. Shweta Singh",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Ms. Divya Menon",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Ms. Divya Menon",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Mrs. Shweta Singh",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Mr. Vijay Singh",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Ms. Preeti Sharma",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Ms. Preeti Sharma",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Dr. Anand Kumar",
    student: "Rahul Gupta",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Ms. Anjali Dubey",
    student: "Priya Sharma",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Mr. Ramesh Iyer",
    student: "Arjun Reddy",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Mrs. Shweta Singh",
    student: "Neha Singh",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Ms. Divya Menon",
    student: "Siddharth Menon",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Ms. Divya Menon",
    student: "Ananya Rao",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Mrs. Shweta Singh",
    student: "Rohan Kumar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Mr. Vijay Singh",
    student: "Ishita Parekh",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Ms. Preeti Sharma",
    student: "Aryan Das",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Ms. Preeti Sharma",
    student: "Sonia Devi",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];

export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 6, 14, 8, 0),
    end: new Date(2025, 6, 14, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 14, 9, 0),
    end: new Date(2025, 6, 14, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 14, 10, 0),
    end: new Date(2025, 6, 14, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 14, 11, 0),
    end: new Date(2025, 6, 14, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 14, 13, 0),
    end: new Date(2025, 6, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 14, 14, 0),
    end: new Date(2025, 6, 14, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 15, 9, 0),
    end: new Date(2025, 6, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 15, 10, 0),
    end: new Date(2025, 6, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 15, 11, 0),
    end: new Date(2025, 6, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 15, 14, 0),
    end: new Date(2025, 6, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 6, 16, 8, 0),
    end: new Date(2025, 6, 16, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 16, 10, 0),
    end: new Date(2025, 6, 16, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 16, 13, 0),
    end: new Date(2025, 6, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 16, 14, 0),
    end: new Date(2025, 6, 16, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 17, 9, 0),
    end: new Date(2025, 6, 17, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 6, 17, 10, 0),
    end: new Date(2025, 6, 17, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 17, 11, 0),
    end: new Date(2025, 6, 17, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 17, 14, 0),
    end: new Date(2025, 6, 17, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 6, 18, 8, 0),
    end: new Date(2025, 6, 18, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 6, 18, 9, 0),
    end: new Date(2025, 6, 18, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 6, 18, 11, 0),
    end: new Date(2025, 6, 18, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 6, 18, 13, 0),
    end: new Date(2025, 6, 18, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 6, 18, 14, 0),
    end: new Date(2025, 6, 18, 14, 45),
  },
];